@LaerdalSimDesignerThemeToSimPadConverter.WebAPI_HostAddress = http://localhost:5041

POST {{LaerdalSimDesignerThemeToSimPadConverter.WebAPI_HostAddress}}/api/convert
Accept: application/octet-stream


###
